"""`learn-gateway` — Mode A: the service is the tutor.

IDEA.md *The fork* defines Mode A as "gateway runs the same prompt pack through llm-svc",
and this is the process that does it. Per CONTRACTS.md's stack decision it holds four
things in one process — the gateway routes, ``llm``, ``tutor`` and ``corpus`` — each a
router that can be lifted out later. Only ``learner-svc`` (stateful, its own volume) and
``render-svc`` (Node) are over the network.

What is decided by code and what is generated by a model is the whole design, and the two
never mix here:

* ``tutor/orchestrator.py`` decides. Next question, pass/fail, hint legality, strategy
  change, teach-back due, session end, feasibility.
* ``llm`` generates, through the prompt pack in ``skills/teach/prompts/``. It never
  decides anything, and it never writes durable state.
* ``learner-svc`` recomputes every number. The gateway holds no learner model.

Run it::

    uv run learn-gateway                 # :5033
    uv run learn-gateway --port 5043 --reload
    uvicorn learning_tutor.gateway.app:app --port 5033

Environment: see docs/modules/gateway.md.
"""

from __future__ import annotations

import os
from collections.abc import AsyncIterator
from contextlib import asynccontextmanager
from pathlib import Path
from typing import Any

import httpx
from fastapi import FastAPI, Request
from fastapi.exceptions import RequestValidationError
from fastapi.responses import HTMLResponse, JSONResponse
from fastapi.staticfiles import StaticFiles

from ..config import Settings, get_settings
from ..corpus.router import router as corpus_router
from ..llm.router import router as llm_router
from .deps import Services, build_services
from .errors import GatewayError

TITLE = "learn-gateway"
DESCRIPTION = (
    "One-to-one AI teaching over HTTP: probe -> plan -> teach, with the decisions in "
    "tutor/orchestrator.py and the pedagogy in skills/teach/prompts/."
)
DEFAULT_PORT = 5033

_INDEX = """<!doctype html>
<title>learn-gateway</title>
<style>
 body{font:16px/1.6 system-ui,sans-serif;max-width:46rem;margin:4rem auto;padding:0 1.5rem}
 code{background:#f3f4f6;padding:.1em .35em;border-radius:.25em}
 a{color:#1d4ed8}
</style>
<h1>learn-gateway</h1>
<p>Mode A of Learning Tutor: probe &rarr; plan &rarr; teach. The web UI is not mounted
(set <code>LT_WEB_DIR</code> to a Next.js static export to serve it from here).</p>
<ul>
  <li><a href="/docs">/docs</a> &mdash; the interactive API</li>
  <li><a href="/api/health">/api/health</a> &mdash; learner, render, llm, corpus</li>
  <li><a href="/api/goals">/api/goals</a> &mdash; the goals and their phases</li>
</ul>
"""


def create_app(
    settings: Settings | None = None,
    *,
    services: Services | None = None,
    learner_transport: httpx.BaseTransport | None = None,
    render_transport: httpx.BaseTransport | None = None,
    learner_url: str | None = None,
    render_url: str | None = None,
) -> FastAPI:
    """Build the app.

    ``services`` (or the transport arguments) is how the test suite runs the whole flow
    in-process: pass ``httpx.ASGITransport(app=learner_svc.create_app(settings))`` and no
    socket is ever opened.
    """

    settings = settings or get_settings()
    settings.ensure_dirs()

    @asynccontextmanager
    async def lifespan(running: FastAPI) -> AsyncIterator[None]:
        try:
            yield
        finally:
            running.state.services.close()

    app = FastAPI(title=TITLE, description=DESCRIPTION, version="1.0", lifespan=lifespan)
    app.state.settings = settings
    app.state.services = services or build_services(
        settings,
        learner_transport=learner_transport,
        render_transport=render_transport,
        learner_url=learner_url,
        render_url=render_url,
    )

    @app.exception_handler(GatewayError)
    def _gateway_error(_request: Request, exc: GatewayError) -> JSONResponse:
        return JSONResponse(exc.payload(), status_code=exc.status)

    @app.exception_handler(RequestValidationError)
    def _validation_error(_request: Request, exc: RequestValidationError) -> JSONResponse:
        first = exc.errors()[0] if exc.errors() else {}
        where = ".".join(str(p) for p in first.get("loc", ())[1:]) or "body"
        return JSONResponse(
            {"error": f"{where}: {first.get('msg', 'invalid request')}", "code": "bad_request"},
            status_code=400,
        )

    from .routes import goals, holdouts, ops, plan, probe, sources, study, teach

    for module in (goals, sources, plan, probe, teach, holdouts, study, ops):
        app.include_router(module.router)

    # The two modules that live in this process, mounted where CONTRACTS.md puts them.
    app.include_router(llm_router, prefix="/api")
    app.include_router(corpus_router, prefix="/api")

    web_dir = os.environ.get("LT_WEB_DIR")
    if web_dir and Path(web_dir).is_dir():
        app.mount("/", StaticFiles(directory=web_dir, html=True), name="web-ui")
    else:

        @app.get("/", include_in_schema=False)
        def index() -> HTMLResponse:
            return HTMLResponse(_INDEX)

    return app


_app: FastAPI | None = None


def __getattr__(name: str) -> Any:
    """``learning_tutor.gateway.app:app`` for uvicorn, built on first access.

    Lazily, for the same reason learner-svc does it: importing this module must not read
    the environment or create a data directory.
    """

    if name == "app":
        global _app
        if _app is None:
            _app = create_app()
        return _app
    raise AttributeError(name)
