"""Derived views: ``learner.md`` (what the model reads at session start) and ``state.json``.

``learner.md`` shows **evidence, not decimals** (IDEA.md, *Review response*). Numbers stay
internal: the view names states, counts of independent vs assisted evidence, the last
delayed retrieval, transfer evidence, uncertainty and review priority. There is deliberately
no probability anywhere in it — ``no_decimals`` in the tests enforces that.

Both files are regenerated by code on every write. Nothing here is model-editable;
``notes.md`` is the one prose file the model owns, and only preferences live there.
"""

from __future__ import annotations

import json
import math
import re
from datetime import UTC, date, datetime
from typing import Any

from . import disputes as disputes_mod
from . import evidence as evidence_mod
from . import fsrs_sched
from . import graph as graph_mod
from . import misconceptions as misc_mod
from .models import Summary
from .store import Store, parse_ts, utcnow

ASSISTANCE_LABELS = {
    0: "none",
    1: "encouragement",
    2: "conceptual hint",
    3: "strategic hint",
    4: "procedural hint",
    5: "partial solution",
    6: "worked solution",
}
_DECIMAL = re.compile(r"\d\.\d")


# --------------------------------------------------------------------------- prefs
def read_prefs(store: Store) -> list[str]:
    path = store.settings.notes_path
    if not path.exists():
        return []
    prefs: list[str] = []
    in_section = False
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if stripped.lower().startswith("#"):
            in_section = stripped.lower().lstrip("# ").startswith("pref")
            continue
        if in_section and stripped.startswith(("-", "*")):
            prefs.append(stripped.lstrip("-* ").strip())
        elif stripped.lower().startswith("prefs:"):
            prefs.extend(p.strip() for p in stripped.split(":", 1)[1].split("·") if p.strip())
    return [p for p in prefs if p]


# --------------------------------------------------------------------------- pieces
def _goal_row(store: Store, goal_id: str) -> dict[str, Any]:
    row = store.one("SELECT * FROM goals WHERE goal_id = ?", (goal_id,))
    if not row:
        from .store import LearnerError

        raise LearnerError(f"unknown goal {goal_id!r}")
    return dict(row)


def feasibility(store: Store, goal: dict[str, Any], remaining_nodes: int) -> dict[str, Any]:
    settings = store.settings
    minutes = goal.get("minutes_per_session") or 0
    per_session = max(1, minutes // settings.minutes_per_node) if minutes else None
    needed = math.ceil(remaining_nodes / per_session) if per_session else None
    left = None
    if goal.get("deadline"):
        try:
            deadline = date.fromisoformat(goal["deadline"])
        except ValueError:
            deadline = None
        if deadline:
            days = (deadline - datetime.now(UTC).date()).days
            # the goal's own cadence when it has one (migration 3), the env default otherwise
            per_week = goal.get("sessions_per_week") or settings.sessions_per_week
            left = max(0, int(days * per_week / 7))
    return {
        "remaining_nodes": remaining_nodes,
        "nodes_per_session": per_session,
        "sessions_needed": needed,
        "sessions_left": left,
        "tight": bool(needed is not None and left is not None and needed > left),
    }


def _last_session(store: Store, goal_id: str) -> dict[str, Any] | None:
    row = store.one(
        "SELECT * FROM sessions WHERE goal_id = ? ORDER BY started_at DESC LIMIT 1", (goal_id,)
    )
    if not row:
        return None
    events = store.query(
        "SELECT * FROM events WHERE session_id = ? AND kind IN ('answer','probe_answer',"
        "'teach_back') ORDER BY ts",
        (row["session_id"],),
    )
    minutes = None
    if row["ended_at"]:
        elapsed = parse_ts(row["ended_at"]) - parse_ts(row["started_at"])
        minutes = int(elapsed.total_seconds() // 60)
    assistance = [e["assistance_level"] for e in events]
    mean_assistance = round(sum(assistance) / len(assistance)) if assistance else 0
    last_node = None
    for event in reversed(events):
        if event["node_id"]:
            node = store.one("SELECT title FROM nodes WHERE node_id = ?", (event["node_id"],))
            last_node = node["title"] if node else event["node_id"]
            break
    fails_tail = [1 for e in events[-3:] if not e["correct"]]
    return {
        "session_id": row["session_id"],
        "date": row["started_at"][:10],
        "minutes": minutes,
        "answers": len(events),
        "mean_assistance": mean_assistance,
        "mean_assistance_label": ASSISTANCE_LABELS.get(mean_assistance, "none"),
        "stopped_at": last_node,
        "frustration": len(fails_tail) == 3,
        "summary": row["summary"],
    }


def _fragile_line(state) -> str:
    bits = []
    if state.independent_passes:
        bits.append(
            f"{state.independent_passes} independent pass"
            + ("es" if state.independent_passes != 1 else "")
        )
    if state.assisted_passes:
        bits.append(f"{state.assisted_passes} assisted")
    if state.unearned_passes:
        bits.append(f"{state.unearned_passes} at partial-solution level (not counted)")
    if state.self_graded_passes:
        bits.append(f"{state.self_graded_passes} self-graded (not counted)")
    if state.fails:
        bits.append(f"{state.fails} fail" + ("s" if state.fails != 1 else ""))
    if state.last_delayed:
        bits.append(f"last delayed retrieval {state.last_delayed}ed")
    else:
        bits.append("no delayed retrieval yet")
    if state.transfer_passes:
        bits.append(f"{state.transfer_passes} transfer pass")
    else:
        bits.append("no transfer evidence")
    bits.append(f"uncertainty {state.uncertainty}")
    return "; ".join(bits)


# --------------------------------------------------------------------------- summary
def build_summary(store: Store, goal_id: str) -> Summary:
    goal = _goal_row(store, goal_id)
    nodes = graph_mod.get_nodes(store, goal_id)
    node_ids = [n.node_id for n in nodes]
    states = evidence_mod.derive_all(store, node_ids)

    known, unknown = [], []
    fragile: list[dict[str, Any]] = []
    self_graded: list[dict[str, Any]] = []
    misconceptions: list[dict[str, Any]] = []
    for node in nodes:
        state = states[node.node_id]
        if state.self_graded_passes and not state.independent_passes:
            self_graded.append(
                {
                    "node_id": node.node_id,
                    "title": node.title,
                    "self_graded_passes": state.self_graded_passes,
                }
            )
        if state.state == "known":
            known.append(node.title)
        elif state.state == "fragile":
            fragile.append(
                {"node_id": node.node_id, "title": node.title, "evidence": _fragile_line(state)}
            )
        elif state.state == "misconception":
            row = misc_mod.active_for_node(store, node.node_id) or {}
            misconceptions.append(
                {
                    "node_id": node.node_id,
                    "title": node.title,
                    "claim": row.get("claim", state.active_misconception or ""),
                    "state": row.get("state", "active"),
                    "confirmed_on": (row.get("updated_at") or "")[:10],
                }
            )
        else:
            unknown.append(node.title)

    depth = goal.get("depth") or "explain"
    remaining = len(nodes) - len(known)
    feas = feasibility(store, goal, remaining)
    goal_bits = [f"Goal: {goal['title']}", depth]
    goal_bits.append(f"deadline {goal['deadline']}" if goal.get("deadline") else "no deadline")
    if feas["sessions_left"] is not None and feas["sessions_needed"] is not None:
        goal_bits.append(
            f"{feas['sessions_left']} sessions left of ~{feas['sessions_needed']} needed"
            + (" !" if feas["tight"] else "")
        )
    elif feas["sessions_needed"] is not None:
        goal_bits.append(f"~{feas['sessions_needed']} sessions needed")
    goal_line = " · ".join(goal_bits)

    collapsed = _collapsed(store, goal_id, node_ids)
    return Summary(
        goal_id=goal_id,
        generated_at=utcnow(),
        goal_line=goal_line,
        known=known,
        fragile=fragile,
        unknown=unknown,
        self_graded=self_graded,
        misconceptions=misconceptions,
        due_today=fsrs_sched.due_today_count(store, node_ids),
        prefs=read_prefs(store),
        last_session=_last_session(store, goal_id),
        collapsed=collapsed,
        feasibility=feas,
    )


def _collapsed(store: Store, goal_id: str, in_goal: list[str]) -> list[str]:
    """One line per group for known nodes outside the active goal."""

    others = [n for n in graph_mod.get_nodes(store) if n.node_id not in in_goal]
    groups: dict[str, int] = {}
    for node in others:
        state = evidence_mod.derive(store, node.node_id)
        if state.state != "known":
            continue
        label = node.domain
        if not label:
            titles = [
                r["title"]
                for r in store.query(
                    "SELECT g.title FROM goals g JOIN node_goals ng ON ng.goal_id = g.goal_id "
                    "WHERE ng.node_id = ? AND g.goal_id != ?",
                    (node.node_id, goal_id),
                )
            ]
            label = titles[0] if titles else "other"
        groups[label] = groups.get(label, 0) + 1
    return [f"+{count} known in {label}" for label, count in sorted(groups.items())]


# --------------------------------------------------------------------------- render
def render_markdown(summary: Summary) -> str:
    day = summary.generated_at[:10]
    lines = [f"# Learner — {day}", summary.goal_line]
    lines.append(
        "Known:    " + (", ".join(summary.known) + " — independent, delayed passes")
        if summary.known
        else "Known:    (nothing yet)"
    )
    if summary.fragile:
        for entry in summary.fragile:
            lines.append(f"Fragile:  {entry['title']} — {entry['evidence']}")
    else:
        lines.append("Fragile:  (none)")
    lines.append("Unknown:  " + (", ".join(summary.unknown) if summary.unknown else "(none)"))
    for entry in summary.self_graded:
        passes = entry["self_graded_passes"]
        lines.append(
            f"Self-graded: {entry['title']} — {passes} pass"
            + ("es" if passes != 1 else "")
            + " judged by the tutor itself, none counted"
        )
    for entry in summary.misconceptions:
        confirmed = f" — confirmed {entry['confirmed_on']}" if entry["confirmed_on"] else ""
        lines.append(f'Misconception (active): "{entry["claim"]}" on {entry["title"]}{confirmed}')
    lines.append(f"Due today: {summary.due_today} items")
    if summary.prefs:
        lines.append("Prefs: " + " · ".join(summary.prefs))
    if summary.last_session:
        last = summary.last_session
        bits = [last["date"]]
        if last["minutes"] is not None:
            bits.append(f"{last['minutes']} min")
        if last["stopped_at"]:
            bits.append(f"stopped at {last['stopped_at']}")
        bits.append(
            f"mean assistance {last['mean_assistance']} ({last['mean_assistance_label']})"
        )
        bits.append("frustration flagged" if last["frustration"] else "no frustration")
        lines.append("Last session: " + ", ".join(bits))
    for line in summary.collapsed:
        lines.append(line)
    text = "\n".join(lines) + "\n"
    return text


def has_decimals(text: str) -> bool:
    return bool(_DECIMAL.search(text))


# --------------------------------------------------------------------------- write
def build_state(store: Store) -> dict[str, Any]:
    goals = [dict(r) for r in store.query("SELECT * FROM goals ORDER BY created_at")]
    nodes = graph_mod.get_nodes(store)
    node_states = {
        node.node_id: evidence_mod.derive(store, node.node_id).model_dump() for node in nodes
    }
    edges = [e.model_dump() for e in graph_mod.get_edges(store)]
    return {
        "generated_at": utcnow(),
        "schema_version": store.schema_version(),
        "graph_version": graph_mod.current_version(store),
        "goals": goals,
        "nodes": {n.node_id: n.model_dump() for n in nodes},
        "node_states": node_states,
        "edges": edges,
        "due_today": fsrs_sched.due_today_count(store),
        "open_disputes": disputes_mod.open_disputes(store),
        "misconceptions": [
            rows
            for rows in (misc_mod.for_node(store, node.node_id) for node in nodes)
            if rows
        ],
    }


def write_state(store: Store) -> str:
    store.settings.ensure_dirs()
    path = store.settings.state_path
    path.write_text(json.dumps(build_state(store), indent=2, default=str), encoding="utf-8")
    return str(path)


def write_learner_md(store: Store, goal_id: str) -> tuple[str, str]:
    summary = build_summary(store, goal_id)
    text = render_markdown(summary)
    store.settings.ensure_dirs()
    path = store.settings.learner_md_path
    path.write_text(text, encoding="utf-8")
    return str(path), text


def refresh(store: Store, goal_id: str | None = None) -> dict[str, Any]:
    """Regenerate every derived file. Called after every write."""

    out: dict[str, Any] = {"state": write_state(store)}
    if goal_id:
        path, _text = write_learner_md(store, goal_id)
        out["learner_md"] = path
    return out
