"""Read routes: what to ask next, the two views, the raw rows, holdouts, metrics, export.

Nothing here writes evidence. ``summary``, ``export`` and ``passport`` do rewrite the
derived files — that is the point of them: the views are regenerated by code, never
edited.

``events``, ``disputes``, ``misconceptions`` and ``passport`` exist so that no caller
needs a second, direct connection to ``events.db`` to answer "why is this node fragile?"
or to export the learner. Before them the gateway opened the database itself; that
fallback is gone.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from fastapi import APIRouter, Depends, Response
from fastapi.responses import PlainTextResponse

from ...learner import api
from ...learner.store import LearnerError, Store
from ..deps import get_store

router = APIRouter(prefix="/v1", tags=["reads"])


@router.get("/next")
def next_(
    goal: str | None = None,
    mode: str = "auto",
    n: int = 1,
    session: str | None = None,
    store: Store = Depends(get_store),
) -> dict[str, Any]:
    """Pick what to ask next. Never returns a holdout item, in any mode."""

    goal_id = api.resolve_goal(store, goal)
    return api.next_(store, goal_id, mode=mode, n=n, session_id=session)


@router.get("/summary/{goal_id}")
def summary(goal_id: str, format: str = "md", store: Store = Depends(get_store)):
    """``format=md`` returns the markdown the CLI prints, as ``text/markdown``."""

    from ...learner.store import LearnerError

    if format not in ("md", "json"):
        raise LearnerError("format must be md or json")
    result = api.summary(store, goal_id, format)
    if format == "md":
        return PlainTextResponse(result["markdown"], media_type="text/markdown")
    return result


@router.get("/events")
def events(
    goal: str | None = None,
    node: str | None = None,
    session: str | None = None,
    kind: str | None = None,
    since: str | None = None,
    limit: int = api.DEFAULT_EVENT_LIMIT,
    store: Store = Depends(get_store),
) -> dict[str, Any]:
    """Raw event rows, newest first, capped at 1000.

    Every filter is optional and they intersect. ``since`` is an ISO-8601 timestamp
    compared against ``ts``.
    """

    return api.events(
        store,
        goal_id=goal,
        node_id=node,
        session_id=session,
        kind=kind,
        since=since,
        limit=limit,
    )


@router.get("/disputes")
def disputes(
    goal: str | None = None,
    status: str | None = None,
    node: str | None = None,
    store: Store = Depends(get_store),
) -> dict[str, Any]:
    """Typed disputes. ``node`` is a superset of the contracted ``?goal=&status=``, and it
    is what a per-node receipt needs."""

    return api.disputes(store, goal_id=goal, node_id=node, status=status)


@router.get("/misconceptions")
def misconceptions(
    goal: str | None = None,
    node: str | None = None,
    state: str | None = None,
    store: Store = Depends(get_store),
) -> dict[str, Any]:
    """Misconceptions with their confirmation steps. ``state`` is one of
    suspected|active|weakened|resolved|recurred."""

    return api.misconceptions(store, goal_id=goal, node_id=node, state=state)


@router.get("/passport")
def passport(
    goal: str | None = None, format: str = "zip", store: Store = Depends(get_store)
):
    """The learner passport: ``application/zip`` by default, the raw tables as JSON with
    ``format=json``.

    The zip holds ``events.jsonl``, ``state.json``, ``learner.md``, ``notes.md``,
    ``goals.json``, ``graph.json``, ``disputes.json``, the vault's session logs under
    ``artifacts/sessions/`` and a ``MANIFEST.json`` naming the source of each member.
    """

    from ...learner.store import LearnerError

    if format not in ("zip", "json"):
        raise LearnerError("format must be zip or json")
    if format == "json":
        return api.passport(store, goal)
    if goal:
        api.goal_get(store, goal)
    name = f"learner-passport{'-' + goal if goal else ''}.zip"
    return Response(
        content=api.passport_zip(store, goal),
        media_type="application/zip",
        headers={"Content-Disposition": f'attachment; filename="{name}"'},
    )


@router.get("/holdouts/{goal_id}/due")
def holdouts_due(goal_id: str, store: Store = Depends(get_store)) -> dict[str, Any]:
    api.goal_get(store, goal_id)
    return api.holdout_check(store, goal_id)


@router.get("/metrics/{goal_id}")
def metrics(goal_id: str, store: Store = Depends(get_store)) -> dict[str, Any]:
    api.goal_get(store, goal_id)
    return api.metrics(store, goal_id)


@router.get("/export")
def export(out: str | None = None, store: Store = Depends(get_store)) -> dict[str, Any]:
    """Write ``events.jsonl``. Over HTTP, ``out`` may only name a file inside the data
    directory (relative paths are taken relative to it), so a caller cannot make the service
    write anywhere else on the host."""

    if out is None:
        return api.export(store, None)
    data_dir = store.settings.data_dir.resolve()
    target = Path(out)
    target = (target if target.is_absolute() else data_dir / target).resolve()
    if not target.is_relative_to(data_dir):
        raise LearnerError(f"out must be a path inside the data directory, got {out!r}")
    return api.export(store, str(target))
